
generic_hw_control_loop:
  loop_hz: 50 # not faster than 250hz or you could randomly lose data (if sended via USB)
  cycle_time_error_threshold: 0.1

hardware_interface:
  joints:
    - Joint_12
    - Joint_23
    - Joint_34
    - Joint_45
    - Joint_56
    - Joint_6G

# Nice list of controllers: https://www.rosroboticslearning.com/ros-control
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 200

position_trajectory_controller:
  type: position_controllers/JointTrajectoryController # TODO JointGroupPositionController for jogging https://ros-planning.github.io/moveit_tutorials/doc/realtime_servo/realtime_servo_tutorial.html
  joints:
    - Joint_12
    - Joint_23
    - Joint_34
    - Joint_45
    - Joint_56
    - Joint_6G
