
generic_hw_control_loop:
  loop_hz: 200
  cycle_time_error_threshold: 0.1

hardware_interface:
  joints:
    - Joint_12
    - Joint_23
    - Joint_34
    - Joint_45
    - Joint_56
    - Joint_6G

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 200

position_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - Joint_12
    - Joint_23
    - Joint_34
    - Joint_45
    - Joint_56
    - Joint_6G
